### ISSUE TITLE
1.8 - [MOBILE] COMPONENTE CARD PARCEIROS

### ISSUE THREAD

**Issue by daniellsfilho** [ProManage-FatecSJC/pro-manager-mobile#21]
**Requisitos:**
_Nenhum_

Card de parceiro contendo foto, nome, status e nome do responsável

**DoD:**
- [x]  ícone de foto de perfil
- [x] nome
- [x] status
- [x] nome do responsável

**Wireframe exemplo:**

![Image](https://user-images.githubusercontent.com/79336346/234620863-d858ec69-67bd-43cc-8456-246cbf6ea517.png)

Aplicar alterações se necessário

**Comment by annakks** [comment]
iniciado 28/04
finalizado dia 30/04
