### ISSUE TITLE
1.18 - [MOBILE] LISTAGEM DE PARCEIROS

### ISSUE THREAD

**Issue by daniellsfilho** [ProManage-FatecSJC/pro-manager-mobile#22]
Tela de listagem de parceiros:

**Pré-requisitos:**
- [x] Card 1.8

Será acessada ao clicar em um dos cards da tela Home. Deverá filtrar os parceiros de acordo com o card selecionado, não filtrar se o card "Total de parceiros" for clicado.

**DoD:**
- [x] Navegação da tela home para esta tela;
- [x] Listagem de acordo com filtro;
- [x] Listagem sem filtros (caso "Total de parceiros")

**Wireframe exemplo:**

![Image](https://user-images.githubusercontent.com/79336346/234627720-d1c57aa1-b8d1-414d-9091-bedb8d098c77.png)

Fazer alterações se necessário.

**Comment by annakks** [comment]
iniciado dia 30/04
finalizado dia 05/05
