### ISSUE TITLE
1.23 - [MOBILE] BARRA DE PESQUISA (LISTAGEM DE PARCEIROS)

### ISSUE THREAD

**Issue by daniellsfilho** [ProManage-FatecSJC/pro-manager-mobile#23]
Barra de pesquisa na tela de listagem de parceiros:

**Requisitos:**
- [x] Card 1.18

Barra de pesquisa na área superior da listagem de parceiros.

**DoD:**
- [x] Filtrar os parceiros da listagem de acordo com o que for digitado.

**Wireframe exemplo:**

![Image](https://user-images.githubusercontent.com/79336346/234629184-fb907598-94f0-4d7b-aab6-2fa6c8b03f8c.png)

**Comment by annakks** [comment]
iniciado dia 02/05
finalizado dia 05/05
