### ISSUE TITLE
1.12 - [MOBILE] DETALHES DO PARCEIRO

### ISSUE THREAD

**Issue by daniellsfilho** [ProManage-FatecSJC/pro-manager-mobile#24]
**Requisitos:**
- [x] Card 1.18

Tela contendo informações do parceiro selecionado na tela de listagem. Acessar essa tela clicando em um card da listagem de parceiros

**DoD:** 
- [x] Navegar para a tela a partir do card da tela de listagem;
- [x] Ícone de foto no topo da tela;
- [x] Resgatar informações gerais do parceiro;
- [x] Botões no final da página (sem funcionalidade)

**Wireframe exemplo:**

![Image](https://user-images.githubusercontent.com/79336346/234730594-4c076090-8942-4438-b11d-22d65051ee57.png)

Alterar estilização como quiser,  só avisar antes de mudar

**Comment by annakks** [comment]
Finalizado dia 10/05
