### ISSUE TITLE
[MOBILE] CADASTRO DE USUÁRIOS

### ISSUE THREAD

**Issue by bruno-pisciotta281** [ProManage-FatecSJC/pro-manager-mobile#35]
**Requisitos:**
_Nenhum_

Página de cadastro de usuários, acessada somente por usuários administradores

**DoD:**
- [x] Campos necessários para cadastrar usuário mostrados no wireframe exemplo;
- [x] Botão cancelar voltando para a tela de perfil;
- [x] Acesso será feito por um botão na tela de perfil do usuário;
- [x] Select de cargo contendo os cargos disponíveis no sistema (admin / observer);
- [ ] Verificação de email;
- [x] Salvar usuário no banco.

**Wireframe exemplo:**

![Image](https://user-images.githubusercontent.com/79336346/235188735-2fa93159-e948-4db1-9834-cfec10453605.png)

Aplicar alterações se necessário

**Comment by annakks** [comment]
inicio 22/05
