### ISSUE TITLE
[MOBILE] EDITAR PARCEIROS

### ISSUE THREAD

**Issue by bruno-pisciotta281** [ProManage-FatecSJC/pro-manager-mobile#36]
**Pré-Requisitos:**
- [x] Tela de Informações do parceiro.

**Descrição:**
Será acessada ao clicar em "Editar" na tela de detalhes do parceiro, conterá os campos do parceiro já preenchidos com os dados existentes e abertos à edição, e botões salvar e cancelar

**DoD:**
- [x] Navegação da tela de detalhes do parceiro para essa tela;
- [x] Campos do wireframe exemplo;
- [x] Atualizar parceiro no banco;
- [x] Botão cancelar voltar à tela de listagem.

**Wireframe exemplo:**

![Image](https://user-images.githubusercontent.com/79336346/235554212-5e96bb31-b8e5-40eb-b497-5e1e66a52f78.png)

Fazer alterações se necessário.

**Comment by annakks** [comment]
inicio 30/05

**Comment by annakks** [comment]
finish 01/06
