### ISSUE TITLE
[MOBILE] EDIÇÃO DE USUÁRIOS

### ISSUE THREAD

**Issue by bruno-pisciotta281** [ProManage-FatecSJC/pro-manager-mobile#38]
**Pré-Requisitos:**
- [x] Tela de perfil;
- [x] Tela de detalhes do usuário

**Descrição:**
Tela de edição de dados do usuário. Dados editaveis: nome, cargo, email e senha. Ao ser acessada por usuários admin, é possível mudar o cargo, senão este campo será desabilitado.

**DoD:**
- [x] Acesso à tela;
- [x] Trazer dados corretos do banco;
- [x] Permitir edição dos campos;
- [x] Atualizar no banco.

**Wireframe exemplo:**

![Image](https://github.com/ProManage-FatecSJC/pro-manager-mobile/assets/79336346/54d173c5-ebd4-46c9-891c-15531de26292)

**Comment by annakks** [comment]
inicio 22/05

**Comment by annakks** [comment]
finish 30/05
