### ISSUE TITLE
[MOBILE] REMODELAÇÃO DA PÁGINA DE PERFIL

### ISSUE THREAD

**Issue by bruno-pisciotta281** [ProManage-FatecSJC/pro-manager-mobile#43]
**Pré-Requisitos:**
_Nenhum_

**Descrição:**
Adição de botões de edição e exclusão de usuários, e campos visíveis nome, email e role sem possibilidade de edição.

**DoD:**
- [x] Campos nome, email e role;
- [x] Botão de navegação para página de edição de usuário;
- [x] Botão de exclusão de usuário;

**Wireframe exemplo:**

![Image](https://github.com/ProManage-FatecSJC/pro-manager-mobile/assets/79336346/58d73aac-4cb4-4db4-b6ed-c2e07f4f74fe)

**Comment by annakks** [comment]
inicio 29/05

**Comment by annakks** [comment]
finish 30/05
